### ISSUE TITLE
execute[apt-cache gencaches] cannot be found in the resource collection

### ISSUE THREAD

**Issue by manuelmazzuola** [chef-cookbooks/apt#205]
### Cookbook version
2.7.0

### Chef-client version
chef-solo 12.6.0

### Platform Details
```
Description:    Ubuntu 14.04.2 LTS
Linux test-cd-base 3.16.0-31-generic #43~14.04.1-Ubuntu SMP Tue Mar 10 20:13:38 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
GCE
```

### Scenario:
```
# Install libsigar
  apt_repository 'libsigar' do
    action        :add
    uri        'myrepo'
    distribution  node['lsb']['codename']
    components    [ 'main' ]
    keyserver     'keyserver.ubuntu.com'
    key           'AKSLDASLD'
  end
```

### Actual Result
```
 ================================================================================
           Error executing action `add` on resource 'apt_repository[libsigar]'
           ================================================================================
           
           Chef::Exceptions::ResourceNotFound
           ----------------------------------
           resource execute[apt-get update] is configured to notify resource execute[apt-cache gencaches] with action run, but execute[apt-cache gencaches] cannot be found in the resource collection. execute[apt
-get update] is defined in /tmp/kitchen/cookbooks/apt/providers/repository.rb:156:in `block in class_from_file'
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_collection.rb:45:in `find_local'
           /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_collection.rb:58:in `find'
           /tmp/kitchen/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
```

**Comment by sharmavipul** [comment]
facing same issue....

**Comment by jaredstehler** [comment]
seems `compat_resource` was released yesterday with breaking changes. `12.9.1` works for me, `12.10.1` gives me this error.

**Comment by sharmavipul** [comment]
Yeah...Tested the above...Locked to earlier version

**Comment by thommay** [comment]
@lamont-granquist

**Comment by manuelmazzuola** [comment]
@jaredstehler thanks

**Comment by lamont-granquist** [comment]
closing as a dup of chef-cookbooks/compat_resource#54
