### ISSUE TITLE
Recipe cacher-client fails with compiletime

### ISSUE THREAD

**Issue by klamontagne** [chef-cookbooks/apt#93]
The cacher-client recipe fails to compile if:
- node['apt']['compiletime'] == true
- apt::cacher-client is in the run_list before apt::default

apt::default must be in the run_list before apt::cacher-client, but this executes `apt-get update` without the proxy.

---

```
Recipe: apt::cacher-client
  * template[/etc/apt/apt.conf.d/01proxy] action create

    ================================================================================
    Recipe Compile Error in .../cookbooks/apt/recipes/cacher-client.rb
    ================================================================================

    Chef::Exceptions::ResourceNotFound
    ----------------------------------
    resource template[/etc/apt/apt.conf.d/01proxy] is configured to notify
    resource execute[apt-get update] with action run, but
    execute[apt-get update] cannot be found in the resource collection.
    template[/etc/apt/apt.conf.d/01proxy] is defined in
    /var/chef/cache/cookbooks/apt/recipes/cacher-client.rb:60:in `from_file'

    Cookbook Trace:
    ---------------
      /var/chef/cache/cookbooks/apt/recipes/cacher-client.rb:73:in `from_file'

    Relevant File Content:
    ----------------------
    /var/chef/cache/cookbooks/apt/recipes/cacher-client.rb:

     66:        :proxy => cacher_ipaddress,
     67:        :port => servers[0]['apt']['cacher_port'],
     68:        :bypass => node['apt']['cache_bypass']
     69:        )
     70:      action(node['apt']['compiletime'] ? :nothing : :create)
     71:      notifies :run, 'execute[apt-get update]', :immediately
     72:    end
     73>>   t.run_action(:create) if node['apt']['compiletime']
     74:  else
     75:    Chef::Log.info('No apt-cacher-ng server found.')
     76:    file '/etc/apt/apt.conf.d/01proxy' do
     77:      action :delete
     78:    end
     79:  end
     80:
     81:  include_recipe 'apt::default'
     82:
```

**Comment by tas50** [comment]
apt::default is always going to need to be on the runlist first. We need to make sure the cache has been warmed up first.
